### ENVIRONMENT VARIABLES ######################################################

# You'll probably want to overwrite $TITLE and $TITLEID with values specific
# to your project. Set $STATIC_DIR to change the directory for static files:
# default is `static`.

[env]
# Project information
TITLE = "Rust Project"
TITLEID = "RUST00001"
# Build configuration
STATIC_DIR = "static"
CARGO_TARGET_DIR = { script = ["echo ${CARGO_TARGET_DIR:=target}"] }
# Compilation specific
RUST_TARGET = "armv7-vita-eabihf"
CARGO_OUT_DIR = "${CARGO_TARGET_DIR}/${RUST_TARGET}/release"
CC="arm-vita-eabi-gcc"
LINKER = "arm-vita-eabi-gcc"
LINKER_FLAGS = "-Wl,-q"
LINKER_SPECS = "${CARGO_OUT_DIR}/specs"


### CLEAN ######################################################################

[tasks.clean-common]
description = "Clean the `common.toml` file from the project directory."
script_runner = "@shell"
script = ["rm -f common.toml"]

[tasks.clean]
dependencies = ["clean-common"]


### DEFAULT: VPK ###############################################################

[tasks.default]
alias = "vpk"


### COMPILER SPECS #############################################################

[tasks.patch-cc-specs]
description = "Remove default `libc` linkage from the linker specs."
script = [
  '${LINKER} -dumpspecs > "${LINKER_SPECS}"',
  'sed -i "s/%{!shared:%{g*:-lg} %{!p:%{!pg:-lc}}%{p:-lc_p}%{pg:-lc_p}}//g" "${LINKER_SPECS}"',
  'sed -i "s/crt0%O%s//g" "${LINKER_SPECS}"'
]

[tasks.get-target-specs]
description = "Download target specs from the `vita-rust/common` git repository."
env = { TARGET_JSON_URL = "https://github.com/vita-rust/common/raw/master/${RUST_TARGET}.json"}
condition_script = [ 'test ! -f "${CARGO_TARGET_DIR}/${RUST_TARGET}.json"' ]
script = [ 
    'mkdir -p "${CARGO_TARGET_DIR}"',
    'curl -SsL "${TARGET_JSON_URL}" > "${CARGO_TARGET_DIR}/${RUST_TARGET}.json"',
]



### BUILD ######################################################################

[tasks.xbuild]
description = "Build the project using `xargo`."
dependencies = ["get-target-specs"]
install_crate = "xargo"
#script = [
#    'xargo build --target=armv7-vita-eabifh --release -vv',
#]
command = "xargo"
args = ["build", "--target=armv7-vita-eabihf", "--release", "-vv"]

[tasks.xbuild.env]
# We need an absolute path to the rustc specs, so we make sure we have one.
RUST_TARGET_PATH = { script = [
    '''
    if [ "${CARGO_TARGET_DIR}" == "${CARGO_TARGET_DIR#/}" ]; then
      echo "${CARGO_MAKE_WORKING_DIRECTORY}/${CARGO_TARGET_DIR}"
    else
      echo "${CARGO_TARGET_DIR}"
    fi
    '''
]}

### DISTRIBUTION TASKS #########################################################

[tasks.elf]
description = "Build an ELF executable using the `vitasdk` linker."
dependencies = ["xbuild", "patch-cc-specs"]
script = [
    """
    ${LINKER} ${LINKER_FLAGS} \
        -specs="${LINKER_SPECS}" \
        -L"${CARGO_OUT_DIR}" \
        -l"${CARGO_MAKE_CRATE_FS_NAME}" \
        -o"${CARGO_OUT_DIR}/${CARGO_MAKE_CRATE_NAME}.elf"
    """
]

[tasks.velf]
description = "Build an VELF executable from the obtained ELF file."
dependencies = ["elf"]
script = [
  """
  arm-vita-eabi-strip -g "${CARGO_OUT_DIR}/${CARGO_MAKE_CRATE_NAME}.elf"
  """,
  """
  vita-elf-create \
      "${CARGO_OUT_DIR}/${CARGO_MAKE_CRATE_NAME}.elf" \
      "${CARGO_OUT_DIR}/${CARGO_MAKE_CRATE_NAME}.velf"
  """
]

[tasks.eboot-bin]
description = "Build an `eboot.bin` file fromt the obtained VELF file."
dependencies = ["velf"]
script = [
  """
  vita-make-fself -s \
      "${CARGO_OUT_DIR}/${CARGO_MAKE_CRATE_NAME}.velf" \
      "${CARGO_OUT_DIR}/eboot.bin"
  """
]

[tasks.param-sfo]
description = "Build the `param.sfo` manifest using with given TITLE and TITLEID."
script = [
    """
    vita-mksfoex \
        -s TITLE_ID="${TITLEID}" \
        "${TITLE}" \
        "${CARGO_OUT_DIR}/param.sfo"
    """
]

[tasks.manifest]
description = "List all static resources into a manifest file."
script = [
  'mkdir -p "${CARGO_OUT_DIR}"',
  '''
  if [ -d "${STATIC_DIR}" ]; then
    find "${STATIC_DIR}" -type f > "${CARGO_OUT_DIR}/MANIFEST"
  else
    echo -n > "${CARGO_OUT_DIR}/MANIFEST"
  fi
  '''
]

[tasks.vpk]
description = "Build a VPK distribution of the project executable and resources."
dependencies = ["manifest", "eboot-bin", "param-sfo"]
script = [
  '''
  VITA_PACK_VPK_FLAGS=$(
    set +x;
    while read -r line; do
      echo -n "--add $line=${line#${STATIC_DIR%/}/} ";
    done < "${CARGO_OUT_DIR}/MANIFEST"
  )
  ''',
  """
  vita-pack-vpk \
          -s "${CARGO_OUT_DIR}/param.sfo" \
          -b "${CARGO_OUT_DIR}/eboot.bin" \
          ${VITA_PACK_VPK_FLAGS} \
          "${CARGO_OUT_DIR}/${CARGO_MAKE_CRATE_NAME}.vpk"
  """
]
